[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "discord-py>=2.5.0",
    "gspread>=6.2.0",
    "oauth2client>=4.1.3",
    "python-dotenv>=1.0.1",
]
