{pkgs}: {
  deps = [
    pkgs.libcxx
    pkgs.openssl
    pkgs.grpc
    pkgs.c-ares
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.chromedriver
    pkgs.xcodebuild
    pkgs.gn
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.awsebcli
    pkgs.cacert
    pkgs.xsimd
    pkgs.which
    pkgs.libpng
    pkgs.libjpeg_turbo
    pkgs.libxcrypt
    pkgs.cairo
    pkgs.unzip
    pkgs.openal
    pkgs.libpulseaudio
    pkgs.libGLU
    pkgs.libGL
    pkgs.gtk2-x11
    pkgs.gdk-pixbuf
    pkgs.freetype
    pkgs.fontconfig
    pkgs.ffmpeg-full
    pkgs.glibcLocales
    pkgs.pkg-config
    pkgs.openssh
    pkgs.hdf5
  ];
}
